### ISSUE TITLE
process.env.MONGODO_URL undefined

### ISSUE THREAD

**Issue by maotongjian** [pawanpk87/myShop-Ecommerce-website#6]
Can you give me a copy of your env file? I'm getting an error when I start your project now. I want to see the actual effect of your project.

**Comment by pawanpk87** [comment]
I have added a sample env file. https://github.com/pawanpk87/myShop-Ecommerce-website/blob/main/sample_ENV_file.txt

**Comment by pawanpk87** [comment]
added a sample env file. https://github.com/pawanpk87/myShop-Ecommerce-website/blob/main/sample_ENV_file.txt
